/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sneha jain
 */
public class input extends javax.swing.JFrame {

    /**
     * Creates new form input
     */
    public input() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Add_Room = new javax.swing.JButton();
        Add_department = new javax.swing.JButton();
        Add_Instructor = new javax.swing.JButton();
        Add_MeetingTime = new javax.swing.JButton();
        Add_course = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Timetable Generator");

        Add_Room.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Add_Room.setText("Add Rooms");
        Add_Room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_RoomActionPerformed(evt);
            }
        });

        Add_department.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Add_department.setText("Add Departments");
        Add_department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_departmentActionPerformed(evt);
            }
        });

        Add_Instructor.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Add_Instructor.setText("Add Instructors");
        Add_Instructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_InstructorActionPerformed(evt);
            }
        });

        Add_MeetingTime.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Add_MeetingTime.setText("Add Meeting Times");
        Add_MeetingTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_MeetingTimeActionPerformed(evt);
            }
        });

        Add_course.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Add_course.setText("Add Courses");
        Add_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_courseActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel5.setText("Dashboard");

        jButton6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton6.setText("Generate Timetable");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Add_MeetingTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Add_Room, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Add_Instructor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Add_department, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Add_course, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jButton6)))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Add_Room)
                        .addGap(24, 24, 24)
                        .addComponent(Add_Instructor)
                        .addGap(18, 18, 18)
                        .addComponent(Add_MeetingTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Add_course)
                        .addGap(18, 18, 18)
                        .addComponent(Add_department)
                        .addGap(101, 101, 101))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_RoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_RoomActionPerformed
        // TODO add your handling code here:
        Add_Rooms addRoomsForm = new Add_Rooms();
    
    // Make the Add_Rooms form visible
    addRoomsForm.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_Add_RoomActionPerformed

    private void Add_departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_departmentActionPerformed
        // TODO add your handling code here:
        Add_Department addRoomsForm = new Add_Department();
    
    // Make the Add_Rooms form visible
    addRoomsForm.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_Add_departmentActionPerformed

    private void Add_InstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_InstructorActionPerformed
        // TODO add your handling code here:
        Add_Instructor addRoomsForm = new Add_Instructor();
    
    // Make the Add_Rooms form visible
    addRoomsForm.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_Add_InstructorActionPerformed

    private void Add_MeetingTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_MeetingTimeActionPerformed
        // TODO add your handling code here:
        Add_MeetingTime addRoomsForm = new Add_MeetingTime();
    
    // Make the Add_Rooms form visible
    addRoomsForm.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_Add_MeetingTimeActionPerformed

    private void Add_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_courseActionPerformed
        // TODO add your handling code here:
        Add_Course addRoomsForm = new Add_Course();
    
    // Make the Add_Rooms form visible
    addRoomsForm.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_Add_courseActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        App.generateAndDisplay();
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new input().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Instructor;
    private javax.swing.JButton Add_MeetingTime;
    private javax.swing.JButton Add_Room;
    private javax.swing.JButton Add_course;
    private javax.swing.JButton Add_department;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
